POST https://clinic-ashen.vercel.app/auth/login
Content-Type: application/json

{"email": "mouhamad5@gmail.com", "password": "clinic123123"}

###

POST https://clinic-ashen.vercel.app/auth/logout
Content-Type: application/json
Authorization: Token d21d7b64e3ee8035cc5c936d6cc5c7717eb00ee7

###

POST https://clinic-ashen.vercel.app/auth/register
Content-Type: application/json

{
    "email": "mouhamad5@gmail.com",
    "password": "clinic123123",
    "first_name": "mouhamad",
    "last_name": "alloush",
    "dob": "2002-05-09",
    "gender": "M",
    "phone": "+963992820554",
    "medical_history":{
        "text": "hello world"
    }
}

###

POST https://clinic-ashen.vercel.app/auth/password_change
Content-Type: application/json
Authorization: Token b54cb2c60376afc11a78e23ffb53ae6712457c6d

{
    "current_password": "clinic123123",
    "new_password": "clinic1231234"
}
