# Generated by Django 4.2.11 on 2025-08-14 14:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_user_medical_history_medicalhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SY', unique=True),
        ),
    ]
