export const APPOINTMENT_REQUEST = "APPOINTMENT_REQUEST";
export const APPOINTMENT_SUCCESS = "APPOINTMENT_SUCCESS";
export const APPOINTMENT_FAIL = "APPOINTMENT_FAIL";

export const ALL_APPOINTMENT_REQUEST = "ALL_APPOINTMENT_REQUEST";
export const ALL_APPOINTMENT_SUCCESS = "ALL_APPOINTMENT_SUCCESS";
export const ALL_APPOINTMENT_FAIL = "ALL_APPOINTMENT_FAIL";

export const USER_APPOINTMENTS_REQUEST = "USER_APPOINTMENTS_REQUEST";
export const USER_APPOINTMENTS_SUCCESS = "USER_APPOINTMENTS_SUCCESS";
export const USER_APPOINTMENTS_FAIL = "USER_APPOINTMENTS_FAIL";

export const MAKE_APPOINTMENT_REQUEST = "MAKE_APPOINTMENT_REQUEST";
export const MAKE_APPOINTMENT_SUCCESS = "MAKE_APPOINTMENT_SUCCESS";
export const MAKE_APPOINTMENT_FAIL = "MAKE_APPOINTMENT_FAIL";

export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_FAIL = "DELETE_APPOINTMENT_FAIL";

export const RECORD_APPOINTMENT_REQUEST = "RECORD_APPOINTMENT_REQUEST";
export const RECORD_APPOINTMENT_SUCCESS = "RECORD_APPOINTMENT_SUCCESS";
export const RECORD_APPOINTMENT_FAIL = "RECORD_APPOINTMENT_FAIL";

export const GET_RECORD_APPOINTMENT_REQUEST = "GET_RECORD_APPOINTMENT_REQUEST";
export const GET_RECORD_APPOINTMENT_SUCCESS = "GET_RECORD_APPOINTMENT_SUCCESS";
export const GET_RECORD_APPOINTMENT_FAIL = "GET_RECORD_APPOINTMENT_FAIL";
