# Generated by Django 5.0.3 on 2024-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_record_recordimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
