# Generated by Django 4.2.11 on 2025-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_recordimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordimage',
            name='gemini_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='recordimage',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='recordimage',
            name='mime_type',
            field=models.CharField(default='png', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recordimage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
